vim.cmd('hi rustKeyword guifg=#edc898')
vim.cmd('hi rustRepeat guifg=#edc898')
vim.cmd('hi rustConditional guifg=#edc898')
vim.cmd('hi rustStorage guifg=#edc898')
vim.cmd('hi rustModPath guifg=#edc898')
vim.cmd('hi rustTrait guifg=#5ca82a')
vim.cmd('hi rustType guifg=#c2e3ac')
vim.cmd('hi rustString guifg=#d68585')
vim.cmd('hi rustBoolean guifg=#d68585')
vim.cmd('hi rustDecNumber guifg=#d68585')
vim.cmd('hi rustCharacter guifg=#d68585')
vim.cmd('hi rustFuncName guifg=#d5b9eb')
vim.cmd('hi rustFuncCall guifg=#d5b9eb')
vim.cmd('hi rustMacro guifg=#a25ed6')
vim.cmd('hi rustOperator guifg=#91c2cf')
vim.cmd('hi rustIdentifier guifg=#e0e0e0')

