
-- require('toggle_lsp_diagnostics').init()


-- require('toggle_lsp_diagnostics').init { underline = true, virtual_text = { prefix = '|', spacing = 3 } }

--     require("trouble").setup {
      -- your configuration comes here
      -- or leave it empty to use the default settings
      -- refer to the configuration section below
-- {
--     position = "bottom", -- position of the list can be: bottom, top, left, right
--     height = 10, -- height of the trouble list when position is top or bottom
--     width = 50, -- width of the list when position is left or right
--     icons = false, -- use devicons for filenames
--     mode = "workspace_diagnostics", -- "workspace_diagnostics", "document_diagnostics", "quickfix", "lsp_references", "loclist"
--     severity = nil, -- nil (ALL) or vim.diagnostic.severity.ERROR | WARN | INFO | HINT
--     fold_open = "", -- icon used for open folds
--     fold_closed = "", -- icon used for closed folds
--     group = true, -- group results by file
--     padding = true, -- add an extra new line on top of the list
--     cycle_results = true, -- cycle item list when reaching beginning or end of list
--
--     multiline = true, -- render multi-line messages
--     indent_lines = true, -- add an indent guide below the fold icons
--     win_config = { border = "single" }, -- window configuration for floating windows. See |nvim_open_win()|.
--     auto_open = true, -- automatically open the list when you have diagnostics
--     auto_close = false, -- automatically close the list when you have no diagnostics
--     auto_preview = true, -- automatically preview the location of the diagnostic. <esc> to close preview and go back to last window
--     auto_fold = false, -- automatically fold a file trouble list at creation
--     auto_jump = {"lsp_definitions"}, -- for the given modes, automatically jump if there is only a single result
--     include_declaration = { "lsp_references", "lsp_implementations", "lsp_definitions"  }, -- for the given modes, include the declaration of the current symbol in the results
--     signs = {
--       -- icons / text used for a diagnostic
--       error = "",
--       warning = "",
--       hint = "",
--       information = "",
--       other = "",
--     },
--     use_diagnostic_signs = false -- enabling this will use the signs defined in your lsp client
-- }
--     }
